# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    #- name: Build an image
    #  run: | 
    #    docker build --no-cache -t brazil-death-data .
    
    - name: Check the branch we're in 
      run: |
        git branch
        ls -a -l merged_data
        
    - name: Check docker-compose
      run: |
        which docker-compose
        
        
    - name: Run the script 
      run: |
        chmod +x run.sh
        ./run.sh
        
    - name: Print logs
      run: |
        echo "<<<<<<<<<<<DOCKER LOGS>>>>>>>>>>>>>>>>"
        cat docker.log
        echo "<<<<<<<<<<<RUN LOGS>>>>>>>>>>>>>>>>>>>"
        cat merged_data/by_state_yearly.out
        
    #- name: Create Pull Request
    #  uses: peter-evans/create-pull-request@v3
    #  with:
    #    title: Latest run
    #    branch: update-data
