on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs/

