on: push

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./
        
      - name: Upload site
        uses: actions/upload-artifact@master 
        with:
          name: merged_files
          path: merged_files/
  
      - name: Upload merged files
        uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs/

      - name: Commit files
        run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: add_workflow

      
